# This is a basic workflow that is manually triggered

name: Sanity Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version of the application'
        # Default value if no value is explicitly provided
        default: 'X'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job 
  build-image:
    runs-on: ubuntu-20.04
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: "Build with Maven"
      run: |
          export TZ="Europe/Paris"
          mvn clean
          mvn test -Dtest="SanityRunner"

    - uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/cucumber.json"
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/cucumber-html-reports
